/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminMenu.java
 *
 * Created on 27-Mar-2012, 10:12:21 AM
 */
package Dossier;

import javax.swing.JOptionPane;

/**
 *
 * @author Shawn
 * Date: Saturday, March 30
 * School: Robert Bateman High School
 * Computer used: Windows 7 pc, 84GB RAM, 1 TB HDD,  Intel I7~Q70
 * IDE used: netbeans 7.0.1
 * Created on Mar 28, 2012, 12:28:17 AM
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * 
     */
    protected static MainMenu a;

    /** Creates new form AdminEventsScreen
     * @param a 
     */
    public AdminMenu(MainMenu a) {
        this.a = a;
        initComponents();
        //Call constructors to set combo boxes properly
        particpantDropDownList();
        eventDropDownList();
        //Set text of number of participants and events
        numberOfParticipants.setText(Integer.toString(secretSantaStore.numberOfParticipantsInStore));
        numberOfEvents.setText(Integer.toString(secretSantaStore.numberOfEventsInStore));
        //Makes sure all of the textfields are uneditable
        firstName.setEditable(false);
        lastName.setEditable(false);
        participantGrade.setEditable(false);
        username.setEditable(false);
        password.setEditable(false);
        title.setEditable(false);
        size.setEditable(false);
        author.setEditable(false);
        grade.setEditable(false);
    }
    //Method that will reconstruct the combobox when called

    /**
     * 
     */
    public void eventDropDownList() {
        //Set maximum row count to number of participants
        String[] x = new String[secretSantaStore.numberOfEventsInStore];
        //Assign rows in terms of items to title of events located in in the event store
        for (int i = 0; i < x.length; i++) {
            x[i] = secretSantaStore.eventsListArray[i].getTitle();
        }
        eventsListComboBox.setModel(new javax.swing.DefaultComboBoxModel(x));
    }
    //Method that will reconstruct the combobox when called

    /**
     * 
     */
    public void particpantDropDownList() {
        //Set maximum row count to number of participants
        String[] x = new String[secretSantaStore.numberOfParticipantsInStore];
        //Assign rows in terms of items to name of participants located in  the participant store
        for (int i = 0; i < x.length; i++) {
            x[i] = secretSantaStore.participantsList[i].getUsername();
        }
        participantComboBox.setModel(new javax.swing.DefaultComboBoxModel(x));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        deleteEvent = new javax.swing.JButton();
        viewEvents = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        blank2 = new javax.swing.JLabel();
        blank = new javax.swing.JLabel();
        numberOfParticipants = new javax.swing.JLabel();
        numberOfEvents = new javax.swing.JLabel();
        eventsListComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        loadEvent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        participantComboBox = new javax.swing.JComboBox();
        deleteUser = new javax.swing.JButton();
        loadParticipant = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numberOfParticipantsInEvent = new javax.swing.JLabel();
        lockEvent = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        participantGrade = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        title = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        searchParticipant = new javax.swing.JButton();
        searchEvent = new javax.swing.JButton();
        participantFirstNameSearch = new javax.swing.JTextField();
        participantLastNameSearch = new javax.swing.JTextField();
        eventAuthorSearch = new javax.swing.JTextField();
        eventTitleSearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setText("Events");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        deleteEvent.setText("Delete");
        deleteEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEventActionPerformed(evt);
            }
        });

        viewEvents.setText("View Event");
        viewEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEventsActionPerformed(evt);
            }
        });

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        blank2.setText("Number of Events:");

        blank.setText("Number of Particiapnts:");

        numberOfParticipants.setText("_");

        numberOfEvents.setText("_");

        eventsListComboBox.setMaximumRowCount(1000);
        eventsListComboBox.setToolTipText("");
        eventsListComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventsListComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Title");

        jLabel6.setText("Author");

        jLabel8.setText("Size");

        jLabel9.setText("Grade");

        loadEvent.setText("Load Event");
        loadEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadEventActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Participants");

        participantComboBox.setMaximumRowCount(10000);
        participantComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantComboBoxActionPerformed(evt);
            }
        });

        deleteUser.setText("Delete user");
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });

        loadParticipant.setText("Load Participant");
        loadParticipant.setToolTipText("Press Load to see the information on the Event youve selected in the Drop down list");
        loadParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadParticipantActionPerformed(evt);
            }
        });

        jLabel10.setText("First Name");

        jLabel11.setText("Last Name");

        jLabel12.setText("Grade");

        jLabel13.setText("Username");

        jLabel14.setText("Password");

        jLabel3.setText("# of Particiapants in Event");

        numberOfParticipantsInEvent.setText("_");

        lockEvent.setText("Lock and Set Event");
        lockEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockEventActionPerformed(evt);
            }
        });

        searchParticipant.setText("Search");
        searchParticipant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchParticipantActionPerformed(evt);
            }
        });

        searchEvent.setText("searchEvent");
        searchEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEventActionPerformed(evt);
            }
        });

        participantFirstNameSearch.setText(" ");

        eventAuthorSearch.setText(" ");

        eventTitleSearch.setText(" ");

        jLabel4.setText("Search Participant");

        jLabel15.setText("search Event");

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(deleteUser)
                .addGap(62, 62, 62)
                .addComponent(blank)
                .addGap(18, 18, 18)
                .addComponent(numberOfParticipants, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(participantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lockEvent)
                                            .addComponent(loadEvent))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eventsListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(loadParticipant))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel15)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(add)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(participantFirstNameSearch, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eventTitleSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(viewEvents)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(deleteEvent)
                        .addGap(183, 183, 183))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(participantLastNameSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(eventAuthorSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchParticipant)
                                    .addComponent(searchEvent))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(participantGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(save)
                            .addComponent(exit))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(numberOfParticipantsInEvent))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(blank2)
                                    .addGap(18, 18, 18)
                                    .addComponent(numberOfEvents))))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(deleteUser)
                    .addComponent(blank)
                    .addComponent(numberOfParticipants))
                .addGap(10, 10, 10)
                .addComponent(participantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadParticipant)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(participantGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchParticipant)
                    .addComponent(participantFirstNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(participantLastNameSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eventAuthorSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eventTitleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchEvent))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eventsListComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteEvent)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(add)
                                    .addComponent(viewEvents))))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(loadEvent)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lockEvent)
                            .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(exit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(back)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfParticipantsInEvent)
                            .addComponent(jLabel3))
                        .addGap(123, 123, 123))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberOfEvents)
                            .addComponent(blank2))
                        .addGap(54, 54, 54))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//Redirects you to the Admin Event Screen Window
private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    this.setVisible(false);
    MainMenu.adminEventScreen.setVisible(true);

}//GEN-LAST:event_addActionPerformed

private void deleteEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEventActionPerformed
   //Removes the currently selected event on the combobox 
    secretSantaStore.removeEventByTitle(secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].title, secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].author);
    //Reconstructs combobox
    eventDropDownList();
}//GEN-LAST:event_deleteEventActionPerformed

private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    //Writes participants and events to file
    secretSantaStore.writeParticpantToFile();
    secretSantaStore.writeEventToFile();
}//GEN-LAST:event_saveActionPerformed
//Exits program
private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    System.exit(0);
}//GEN-LAST:event_exitActionPerformed
 //Rediects you to the Admin View Event SCreen
private void viewEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEventsActionPerformed
    this.setVisible(false);
    MainMenu.adminViewEvent.setVisible(true);
    //Sets global variable eventIndex to the currently selected object on the event combobox
    eventIndex = eventsListComboBox.getSelectedIndex();
}//GEN-LAST:event_viewEventsActionPerformed

private void loadEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadEventActionPerformed
    //sets index to currently selected object
    eventIndex = eventsListComboBox.getSelectedIndex();
    //Sets variables to the attributes of the event selected in the eventsListComboBox
    title.setText(secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].title);
    author.setText(secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].author);
    grade.setText(Integer.toString(secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].grade));
    size.setText(Integer.toString(secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].eventSize));
}//GEN-LAST:event_loadEventActionPerformed

private void eventsListComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventsListComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_eventsListComboBoxActionPerformed

private void participantComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_participantComboBoxActionPerformed

private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
   //Removes participant by first and last name
    secretSantaStore.removeParticipantByName(firstName.getText().trim(), lastName.getText().trim());
    //Reconstructs Combobox
    particpantDropDownList();
    //Save
    secretSantaStore.writeParticpantToFile();
}//GEN-LAST:event_deleteUserActionPerformed
 
private void loadParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadParticipantActionPerformed
 //Sets textfields to the attributes of the currently selected object on the participant combobox
    firstName.setText(secretSantaStore.participantsList[participantComboBox.getSelectedIndex()].getFirstName());
    lastName.setText(secretSantaStore.participantsList[participantComboBox.getSelectedIndex()].getlastName());
    participantGrade.setText(Integer.toString(secretSantaStore.participantsList[participantComboBox.getSelectedIndex()].getGrade()));
    username.setText(secretSantaStore.participantsList[participantComboBox.getSelectedIndex()].getUsername());
    password.setText(secretSantaStore.participantsList[participantComboBox.getSelectedIndex()].getPassword());



}//GEN-LAST:event_loadParticipantActionPerformed
//Sets the lock variable for the event to true and randomizes the list inside the event
private void lockEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockEventActionPerformed
    secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].lock = true;
    secretSantaStore.eventsListArray[eventsListComboBox.getSelectedIndex()].shuffle();
}//GEN-LAST:event_lockEventActionPerformed
//Redirects you to the LogIn screen
private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    this.setVisible(false);
    MainMenu.logIn.setVisible(true);
}//GEN-LAST:event_backActionPerformed

private void searchParticipantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchParticipantActionPerformed
    //Sets index to passed by findBy method
    int indexOfSearchedParticipant = secretSantaStore.findParticipantByName(participantFirstNameSearch.getText().trim(), participantLastNameSearch.getText().trim());
   //If the index is real then set all of the values to the participant with that index
    if (indexOfSearchedParticipant > -1) {
        firstName.setText(secretSantaStore.participantsList[indexOfSearchedParticipant].getFirstName());
        lastName.setText(secretSantaStore.participantsList[indexOfSearchedParticipant].getlastName());
        participantGrade.setText(Integer.toString(secretSantaStore.participantsList[indexOfSearchedParticipant].getGrade()));
        username.setText(secretSantaStore.participantsList[indexOfSearchedParticipant].getUsername());
        password.setText(secretSantaStore.participantsList[indexOfSearchedParticipant].getPassword());
    } //If the index is not real display error message
    else {
        JOptionPane.showMessageDialog(this, "User could not be found",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_searchParticipantActionPerformed

private void searchEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEventActionPerformed
    //Sets index to value retrieved from findBy
    int indexOfSearchedEvent = secretSantaStore.findEventByTitle(eventTitleSearch.getText().trim(), eventAuthorSearch.getText().trim());
   //If Index is real then set all the values to those of object at the above index
    if (indexOfSearchedEvent > -1) {
        title.setText(secretSantaStore.eventsListArray[indexOfSearchedEvent].getTitle());
        author.setText(secretSantaStore.eventsListArray[indexOfSearchedEvent].getAuthor());
        grade.setText(Integer.toString(secretSantaStore.eventsListArray[indexOfSearchedEvent].getGrade()));
        size.setText(Integer.toString(secretSantaStore.eventsListArray[indexOfSearchedEvent].getEventSize()));
    }//Else display error message
    else {
        JOptionPane.showMessageDialog(this, "Event could not be found",
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_searchEventActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField author;
    private javax.swing.JButton back;
    private javax.swing.JLabel blank;
    private javax.swing.JLabel blank2;
    private javax.swing.JButton deleteEvent;
    private javax.swing.JButton deleteUser;
    private javax.swing.JTextField eventAuthorSearch;
    private javax.swing.JTextField eventTitleSearch;
    private javax.swing.JComboBox eventsListComboBox;
    private javax.swing.JButton exit;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton loadEvent;
    private javax.swing.JButton loadParticipant;
    private javax.swing.JButton lockEvent;
    private javax.swing.JLabel numberOfEvents;
    private javax.swing.JLabel numberOfParticipants;
    private javax.swing.JLabel numberOfParticipantsInEvent;
    private javax.swing.JComboBox participantComboBox;
    private javax.swing.JTextField participantFirstNameSearch;
    private javax.swing.JTextField participantGrade;
    private javax.swing.JTextField participantLastNameSearch;
    private javax.swing.JTextField password;
    private javax.swing.JButton save;
    private javax.swing.JButton searchEvent;
    private javax.swing.JButton searchParticipant;
    private javax.swing.JTextField size;
    private javax.swing.JTextField title;
    private javax.swing.JTextField username;
    private javax.swing.JButton viewEvents;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     */
    public int eventIndex;
}
