/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * adminEventScreen.java
 *
 * Created on Mar 28, 2012, 12:28:17 AM
 */
package Dossier;

import javax.swing.JOptionPane;

/**
 *
 * @author Shawn Deol
 * Date: Saturday, March 30
 * School: Robert Bateman High School
 * Computer used: Windows 7 pc, 84GB RAM, 1 TB HDD,  Intel I7~Q70
 * IDE used: netbeans 7.0.1
 * Created on Mar 28, 2012, 12:28:17 AM
 */
public class AdminAddEventScreen extends javax.swing.JFrame {

    /**
     * 
     */
    protected static MainMenu a;

    /** Creates new form adminEventScreen
     * @param a 
     */
    public AdminAddEventScreen(MainMenu a) {
        this.a = a;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        back = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        title = new javax.swing.JTextField();
        author = new javax.swing.JTextField();
        size = new javax.swing.JTextField();
        grade = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Add Event");

        jLabel2.setText("Title");

        jLabel3.setText("Author");

        jLabel4.setText("Grade");

        jLabel5.setText("Size");

        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        title.setText(" ");
        title.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleActionPerformed(evt);
            }
        });

        author.setText(" ");

        grade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9", "10", "11", "12" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(exit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(grade, 0, 77, Short.MAX_VALUE)
                                    .addComponent(author, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(size, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(back))))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exit)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    System.exit(0);

}//GEN-LAST:event_exitActionPerformed
//Sends you back to the Admin Main Menu
private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    this.setVisible(false);
    MainMenu.adminMainMenu.setVisible(true);
}//GEN-LAST:event_backActionPerformed

private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
    //Error check is set to true, any errors will trigger it
    Boolean errorCheck = true;
    //Create temporary participant
    Event p;
    //If any of the textfields are empty an error will pop up and the errorcheck will go off (go false)
    if (title.getText().trim().equals("") || author.getText().trim().equals("") || size.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this, "You msised a spot",
                "Error", JOptionPane.ERROR_MESSAGE);
        errorCheck = false;
        //if the size textfield has been inputted with a word the errorcheck will go off
    } else if (secretSantaStore.hasNum(size.getText().trim())) {
        JOptionPane.showMessageDialog(this, "Size must be a number",
                "Error", JOptionPane.ERROR_MESSAGE);
        errorCheck = false;
    }
    //For loop to run through all events in the store
    for (int i = 0; i < secretSantaStore.numberOfEventsInStore; i++) {
        //If the title already exists the screen will prompt you to choose another title
        if (title.getText().compareTo(secretSantaStore.eventsListArray[i].title) == 0) {
            JOptionPane.showMessageDialog(this, "This title is already taken",
                    "Be more original", JOptionPane.ERROR_MESSAGE);
            //Sets off errorcheck
            errorCheck = false;
        }
    }
    //Case and switch statement to link ComboBox indexes to actual values
    switch (grade.getSelectedIndex()) {
        case 0:
            gradeValue = 9;
            break;
        case 1:
            gradeValue = 10;
            break;
        case 2:
            gradeValue = 11;
            break;
        case 3:
            gradeValue = 12;
            break;
    }
    //If errorcheck remains true and untriggered a new event will be created with the values from the textfields
    if (errorCheck) {
        p = new Event(title.getText().trim(), author.getText().trim(), gradeValue, Integer.parseInt(size.getText().trim()));
        //the new participant will be added to the event array in the store and the file will be saved
        secretSantaStore.addEvent(p);
        secretSantaStore.writeEventToFile();
        //Admin Main Menu pops up and this window collapses
        this.setVisible(false);
        MainMenu.adminMainMenu.setVisible(true);
    }
}//GEN-LAST:event_addActionPerformed

private void titleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_titleActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField author;
    private javax.swing.JButton back;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField size;
    private javax.swing.JTextField title;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     */
    public int gradeValue;
}
