/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogIn.java
 *
 * Created on Mar 26, 2012, 11:09:23 PM
 */
package Dossier;

import javax.swing.JOptionPane;

/**
  * @author Shawn Deol
 * Date: Saturday, March 30
 * School: Robert Bateman High School
 * Computer used: Windows 7 pc, 84GB RAM, 1 TB HDD,  Intel I7~Q70
 * IDE used: netbeans 7.0.1
 * Created on Mar 28, 2012, 12:28:17 AM
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * 
     */
    protected static MainMenu a;

    /** Creates new form LogIn
     * @param a 
     */
    public LogIn(MainMenu a) {
        this.a = a;
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9001 = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        insertUsername = new javax.swing.JTextField();
        insertPassword = new javax.swing.JPasswordField();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9001.setText("Log-In");

        Password.setText("Password");

        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        insertUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertUsernameActionPerformed(evt);
            }
        });

        insertPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPasswordActionPerformed(evt);
            }
        });

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Secret Santa!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Exit)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9001)
                            .addComponent(Password))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insertPassword)
                            .addComponent(insertUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9001)
                    .addComponent(insertUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(insertPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Exit)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void insertUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertUsernameActionPerformed
}//GEN-LAST:event_insertUsernameActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    //Errorcheck Boolean
    Boolean errorCheck = false;
    Participant p;
    //Cycles through accounts and matches input data against stored data
    for (int i = 0; i < secretSantaStore.numberOfParticipantsInStore; i++) {
        p = secretSantaStore.participantsList[i];
        if (p.getUsername().trim().equalsIgnoreCase(insertUsername.getText()) && p.getPassword().trim().equalsIgnoreCase(insertPassword.getText())) {
            //Checks if the user is an admin, if an admin the user is directed
            //to the admin menu and if user they are directed to the user menu
            if (p.user) {
                //Set errorcheck to true to avoid error message
                errorCheck = true;
                //Immediately end loop
                q = p;
                i = secretSantaStore.numberOfParticipantsInStore;
                this.setVisible(false);
                MainMenu.participanMaintMenu.setVisible(true);
            } else if (!p.user) {
                //Set errorcheck to true to avoid error message
                errorCheck = true;
                //Immediately end loop
                q = p;
                i = secretSantaStore.numberOfParticipantsInStore;
                this.setVisible(false);
                MainMenu.adminMainMenu.setVisible(true);

            }
        }

    }
    //Error message in case username/password is incorrect
    if (!errorCheck) {
        JOptionPane.showMessageDialog(this, "Incorrect Username or Password",
                "Error", JOptionPane.ERROR_MESSAGE);
    }


}//GEN-LAST:event_jButton1ActionPerformed

private void insertPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPasswordActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_insertPasswordActionPerformed
//Directs user to register page
private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    insertUsername.setText("");
    insertPassword.setText("");
    MainMenu.registerScreen.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
    System.exit(0);
}//GEN-LAST:event_ExitActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField insertPassword;
    private javax.swing.JTextField insertUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9001;
    // End of variables declaration//GEN-END:variables
    /**
     * 
     */
    public static Participant q;
}
