/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainMenu.java
 *
 * Created on Mar 28, 2012, 10:23:44 AM
 */
package Dossier;

/**
 *
  * @author Shawn Deol
 * Date: Saturday, March 30
 * School: Robert Bateman High School
 * Computer used: Windows 7 pc, 84GB RAM, 1 TB HDD,  Intel I7~Q70
 * IDE used: netbeans 7.0.1
 * Created on Mar 28, 2012, 12:28:17 AM
 */
public class MainMenu extends javax.swing.JFrame {
//Declare screens

    /**
     * 
     */
    protected static AdminAddEventScreen adminEventScreen;
    /**
     * 
     */
    protected static AdminMenu adminMainMenu;
    /**
     * 
     */
    protected static ParticipantMainMenu participanMaintMenu;
    /**
     * 
     */
    protected static ParticipantEventScreen participantEventsScreen;
    /**
     * 
     */
    protected static LogIn logIn;
    /**
     * 
     */
    protected static RegisterScreen registerScreen;
    /**
     * 
     */
    protected static AdminViewEvent adminViewEvent;
    /**
     * 
     */
    protected static ParticipantProfileView participantProfileView;

    /** Creates new form MainMenu */
    public MainMenu() {
        //Create store and Admin Accounts
        secretSantaStore secretSantaStore = new secretSantaStore();
        Participant Admin = new Participant("Admin", "Admin", 9, "a", "b", "c", "Admin", "Root");
        Participant Test1 = new Participant("Test1", "Testb", 9, "a", "d", "c", "Test", "Test");
        Participant Test2 = new Participant("Test2", "Testc", 9, "b", "f", "c", "Test", "Test");
        Participant Test3 = new Participant("Test3", "Testg", 9, "c", "g", "c", "Test", "Test");
        Event testEvent = new Event("Test", "TestAuthor", 9, 10);


        secretSantaStore.writeParticpantToFile();
        secretSantaStore.populateParticipantArrayFromFile();
        secretSantaStore.addParticipant(Admin);
        secretSantaStore.addParticipant(Test1);
        secretSantaStore.addParticipant(Test2);
        secretSantaStore.addParticipant(Test3);
        testEvent.add(Test1);
        testEvent.add(Test2);
        testEvent.add(Test3);
        Admin.setUser(false);
        secretSantaStore.addEvent(testEvent);
        //Connect MainMenu and all classes
        logIn = new LogIn(this);
        adminEventScreen = new AdminAddEventScreen(this);
        adminMainMenu = new AdminMenu(this);
        participantEventsScreen = new ParticipantEventScreen(this);
        adminEventScreen = new AdminAddEventScreen(this);
        participanMaintMenu = new ParticipantMainMenu(this);
        adminViewEvent = new AdminViewEvent(this);
        registerScreen = new RegisterScreen(this);
        participantProfileView = new ParticipantProfileView(this);
        initComponents();
        //Start by making the log in screen visible
        logIn.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
