/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ParticipantEventScreen.java
 *
 * Created on Mar 28, 2012, 12:27:38 AM
 */
package Dossier;

import javax.swing.JOptionPane;

/**
 *
  * @author Shawn Deol
 * Date: Saturday, March 30
 * School: Robert Bateman High School
 * Computer used: Windows 7 pc, 84GB RAM, 1 TB HDD,  Intel I7~Q70
 * IDE used: netbeans 7.0.1
 * Created on Mar 28, 2012, 12:28:17 AM
 */
public class ParticipantEventScreen extends javax.swing.JFrame {

    /**
     * 
     */
    protected static MainMenu a;

    /** Creates new form LogIn
     * @param a 
     */
    public ParticipantEventScreen(MainMenu a) {
        this.a = a;
        initComponents();
        eventDropDownList();
    }

    /**
     * 
     */
    public void eventDropDownList() {
       //Set maximum row count to number of participants
        String[] x = new String[secretSantaStore.numberOfEventsInStore];
        //Assign rows in terms of items to title of events located in in the event store
        for (int i = 0; i < x.length; i++) {
            x[i] = secretSantaStore.eventsListArray[i].getTitle();
        }
        eventComboBox.setModel(new javax.swing.DefaultComboBoxModel(x));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        join = new javax.swing.JButton();
        leave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        viewSantee = new javax.swing.JButton();
        eventComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        join.setText("Join");
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });

        leave.setText("Leave");
        leave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("Event");

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        viewSantee.setText("View Santee");
        viewSantee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSanteeActionPerformed(evt);
            }
        });

        eventComboBox.setToolTipText("");
        eventComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(join)
                        .addGap(275, 275, 275)
                        .addComponent(leave)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(eventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(viewSantee)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(exit)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(exit))
                .addGap(18, 18, 18)
                .addComponent(eventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(join)
                    .addComponent(leave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewSantee)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
    //If the participant and event grades are not equal theyre not allowed on
    if (secretSantaStore.eventsListArray[eventComboBox.getSelectedIndex()].grade != MainMenu.logIn.q.grade) {
        //error
        JOptionPane.showMessageDialog(this, "You must be in the same grade",
                "Error", JOptionPane.ERROR_MESSAGE);
    } //Else if check if the event is locked
    else if (secretSantaStore.eventsListArray[eventComboBox.getSelectedIndex()].lock) {
        JOptionPane.showMessageDialog(this, "Sorry this event is locked please select another",
                "Error", JOptionPane.ERROR_MESSAGE);
    } //else Add participant to event
    //Save winter
    else {
        secretSantaStore.eventsListArray[eventComboBox.getSelectedIndex()].add(MainMenu.logIn.q);
        secretSantaStore.writeEventToFile();
        secretSantaStore.writeParticpantToFile();
    }
}//GEN-LAST:event_joinActionPerformed

private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    secretSantaStore.writeEventToFile();
    secretSantaStore.writeParticpantToFile();
}//GEN-LAST:event_saveActionPerformed
//Exits
private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    System.exit(0);
}//GEN-LAST:event_exitActionPerformed
//Returns Participant to Main Menu
private void leaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveActionPerformed
    MainMenu.participanMaintMenu.setVisible(true);
    this.setVisible(false);
}//GEN-LAST:event_leaveActionPerformed

private void viewSanteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSanteeActionPerformed

}//GEN-LAST:event_viewSanteeActionPerformed

private void eventComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_eventComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox eventComboBox;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton join;
    private javax.swing.JButton leave;
    private javax.swing.JButton save;
    private javax.swing.JButton viewSantee;
    // End of variables declaration//GEN-END:variables
}
